<h1>Getting Started with TFDS</h1>

Example: Fashion MNIST

In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data = tfds.load('fashion_mnist')
for item in mnist_data:
    print(item)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\phani\tensorflow_datasets\fashion_mnist\3.0.1.incompleteT0M0LQ\fashion_mnist-train.tfrecord…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\phani\tensorflow_datasets\fashion_mnist\3.0.1.incompleteT0M0LQ\fashion_mnist-test.tfrecord*…

Dataset fashion_mnist downloaded and prepared to C:\Users\phani\tensorflow_datasets\fashion_mnist\3.0.1. Subsequent calls will reuse this data.
train
test


Load splits into a dataset containing actual data.

In [3]:
mnist_train = tfds.load(name='fashion_mnist', split='train')
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>


Call take(1) to get the first element (record) of the dataset.

In [4]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


Inspect a value in a dataset.

In [5]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


tf.Tensor(2, shape=(), dtype=int64) indicates that this image is class 2 in the MNIST dataset.

Using with_info parameter when loading the dataset, you can get the info about the dataset.

In [6]:
mnist_train, info = tfds.load(name='fashion_mnist', with_info=True)
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='C:\\Users\\phani\\tensorflow_datasets\\fashion_mnist\\3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
   

<h1>Using TFDS with Keras Models</h1>

Same format of data was available in the Keras datasts, with one modification - the shape in TFDS is (28, 28, 1), whereas in the Keras datasets it was (28, 28).

Example: Horses or Humans dataset. 
Code to train a model with it.

In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds

data = tfds.load('horses_or_humans', split='train', as_supervised=True)

train_batches = data.shuffle(100).batch(10)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_batches, epochs=10)

Epoch 1/10



103/103 [==============================] - 35s 296ms/step - loss: 5.6697 - accuracy: 0.8997
Epoch 2/10
103/103 [==============================] - 28s 274ms/step - loss: 0.1181 - accuracy: 0.9649
Epoch 3/10
103/103 [==============================] - 27s 265ms/step - loss: 0.2858 - accuracy: 0.9611
Epoch 4/10
103/103 [==============================] - 27s 260ms/step - loss: 0.2050 - accuracy: 0.9367
Epoch 5/10
103/103 [==============================] - 26s 254ms/step - loss: 0.0437 - accuracy: 0.9825
Epoch 6/10
103/103 [==============================] - 26s 251ms/step - loss: 5.2410e-04 - accuracy: 1.0000
Epoch 7/10
103/103 [==============================] - 25s 242ms/step - loss: 1.1671e-04 - accuracy: 1.0000
Epoch 8/10
103/103 [==============================] - 25s 242ms/step - loss: 6.6329e-05 - accuracy: 1.0000
Epoch 9/10
103/103 [==============================] - 25s 239ms/step - loss: 4.5065e-05 - accuracy: 1.0000
Epoch 10/10
103/103 [==============================] - 25s 240ms/ste

Vadlidation of the model while training by loading a separate validation set from TFDS.

In [2]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

In [3]:
# Batching the validation data.

validation_batches = val_data.batch(32)

In [4]:
history = model.fit(train_batches, epochs=10, validation_data=validation_batches, validation_steps=1)

Epoch 1/10
103/103 [==============================] - 27s 263ms/step - loss: 0.0399 - accuracy: 0.9893 - val_loss: 2.4262 - val_accuracy: 0.9062
Epoch 2/10
103/103 [==============================] - 26s 257ms/step - loss: 0.0378 - accuracy: 0.9932 - val_loss: 2.5622 - val_accuracy: 0.9688
Epoch 3/10
103/103 [==============================] - 27s 259ms/step - loss: 0.0926 - accuracy: 0.9834 - val_loss: 3.1950 - val_accuracy: 0.9375
Epoch 4/10
103/103 [==============================] - 26s 257ms/step - loss: 0.8973 - accuracy: 0.9026 - val_loss: 2.7234 - val_accuracy: 0.8750
Epoch 5/10
103/103 [==============================] - 27s 261ms/step - loss: 0.1939 - accuracy: 0.9367 - val_loss: 3.1259 - val_accuracy: 0.9062
Epoch 6/10
103/103 [==============================] - 27s 257ms/step - loss: 0.1373 - accuracy: 0.9630 - val_loss: 8.7618 - val_accuracy: 0.8750
Epoch 7/10
103/103 [==============================] - 26s 257ms/step - loss: 0.2604 - accuracy: 0.9153 - val_loss: 4.1458 - val_ac

<h1>Using Mapping functions for Augmentation and Tensorflow Addons</h1>

In [5]:
import tensorflow_addons as tfa

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image / 255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

c:\Users\phani\anaconda3\Lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
c:\Users\phani\anaconda3\Lib\site-packages\tensorflow_addons\utils\ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.12.0 and strictly below 2.15.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.15.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure yo

<h1>ETL Process for Managing Data in TensorFlow.</h1>

Consider Horses or Humans classifier.

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_addons as tfa

# Model definition start #
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
# Model definition end #

# Extract Phase Start #
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)
# Extract Phase End #

# Transform phase start #
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image / 255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

train = data.map(augmentimages)
train_batches = data.shuffle(100).batch(32)
validation_batches = val_data.batch(32)
# Transform phase end #

# Load Phase Start #
history = model.fit(train_batches, epochs=10, validation_data=validation_batches, validation_steps=1)
# Load Phase End #

c:\Users\phani\anaconda3\Lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
c:\Users\phani\anaconda3\Lib\site-packages\tensorflow_addons\utils\ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.12.0 and strictly below 2.15.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.15.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure yo




Epoch 1/10



33/33 [==============================] - 23s 558ms/step - loss: 4.1900 - accuracy: 0.7313 - val_loss: 0.4569 - val_accuracy: 0.8750
Epoch 2/10
33/33 [==============================] - 18s 546ms/step - loss: 0.1426 - accuracy: 0.9416 - val_loss: 0.3487 - val_accuracy: 0.9375
Epoch 3/10
33/33 [==============================] - 17s 520ms/step - loss: 0.0475 - accuracy: 0.9825 - val_loss: 0.3565 - val_accuracy: 0.8750
Epoch 4/10
33/33 [==============================] - 17s 520ms/step - loss: 0.0545 - accuracy: 0.9786 - val_loss: 1.0166 - val_accuracy: 0.8125
Epoch 5/10
33/33 [==============================] - 17s 526ms/step - loss: 0.0073 - accuracy: 0.9981 - val_loss: 0.8641 - val_accuracy: 0.8438
Epoch 6/10
33/33 [==============================] - 17s 530ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 1.7438 - val_accuracy: 0.8125
Epoch 7/10
33/33 [==============================] - 17s 528ms/step - loss: 3.9039e-04 - accuracy: 1.0000 - val_loss: 1.8953 - val_accuracy: 0.7812
Epoch 

<h1>Parallelizing ETL to improve training performance.</h1>

Example dataset: Dogs vs. Cats dataset.

In [ ]:
# Accessing raw files that were downloaded.
# Create a list of these files ans use tf.Data.Dataset.list_files to load them.
file_pattern = f'path/to/data/*.tfrecord'
files = tf.data.Dataset.list_files(file_pattern)

In [ ]:
# Loaded into dataset using files.interleave

train_dataset = files.interleave(tf.data.TFRecordDataset, cycle_length=4. num_parallel_calls=tf.data.experimental.AUTOTUNE)

"cycle_length" parameter specifies the number of input elements that are processed concurrently.
'cycle_length = 4', this process will be handling four records at a time.

"num_parallel_calls" parameter specifies the number of parallel calls to execute.

tf.data.experimental.AUTOTUNE, the value is set dynamically based on available CPUs.

Example: If num_parallel_calls is set to 6 after autotuning and cycle_length is 4, you will have 6 separate threads, each running 4 records at a time.